# Site
title: LILO.THINK
subtitle: Metodologia Ágil para Protótipos

# URL
url: http://
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4440
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
